### ISSUE TITLE
500 Cannot assign Joomla\CMS\Object\CMSObject to property Akeeba\Component\Onthos\Administrator\View\Items\HtmlView::$state of type Joomla\Registry\Registry

### ISSUE THREAD

**Issue by peterhulst** [akeeba/onthos#2]
Hello,

After fixing my previous bug report, now the following message came up in J4.4.9:

File &lt;root&gt;/administrator/components/com_onthos/src/View/Items/HtmlView.php Line 95

Debug information
Exception type: TypeError

#0 /var/www/vhosts/loopgroepbedum.nl/joomla4.loopgroepbedum.nl/libraries/src/MVC/Controller/BaseController.php(660): Akeeba\Component\Onthos\Administrator\View\Items\HtmlView->display()
#1 /var/www/vhosts/loopgroepbedum.nl/joomla4.loopgroepbedum.nl/administrator/components/com_onthos/src/Controller/ItemsController.php(62): Joomla\CMS\MVC\Controller\BaseContr

Regards,
Peter

**Comment by nikosdion** [comment]
I made a few changes in https://github.com/akeeba/onthos/commit/0d5c091361e901af4913e55522605a7d4686b50b, https://github.com/akeeba/onthos/commit/01ccb05247829fbe69ea7b4e136a59122b7cf194, and https://github.com/akeeba/onthos/commit/ef39bba3ce4471d50e68951cbdc0de650c6034ca which seem to have solved all the issues in Joomla! 4. Can you please give it a go?

**Comment by peterhulst** [comment]
I have installed again after your modifications. 
The program now starts correctly.
However when I click on e.g. **wrapper** a new '500' is displayed:

Onthos - An unhandled Exception has been detected
**500 Call to undefined method Joomla\CMS\Document\HtmlDocument::getToolbar()
File &lt;root&gt;/administrator/components/com_onthos/src/View/Item/HtmlView.php Line 91**

 The content below this point is for developers and power users.

Joomla 4.4.9 – PHP 8.2.24 on Linux

Debug information
Exception type: Error

#0 /var/www/vhosts/loopgroepbedum.nl/joomla4.loopgroepbedum.nl/administrator/components/com_onthos/src/View/Item/HtmlView.php(76): Akeeba\Component\Onthos\Administrator\View\Item\HtmlView->addToolbar()
#1 /var/www/vhosts/loopgroepbedum.nl/joomla4.loopgroepbedum.nl/libraries/src/MVC/Controller/BaseController.php(660): Akeeba\Component\Onthos\Administrator\View\Item\HtmlView->display()

**Comment by nikosdion** [comment]
Oops, forgot to commit this file. There you go.

**Comment by peterhulst** [comment]
Thank you! Now it works correctly in J4. 
Nice component, but I have to experiment a bit to understand it fully. I already discovered some issues with some installed third-party modules.

Regards,
Peter

**Comment by nikosdion** [comment]
It's a very powerful tool, so be careful. Take a backup before taking any uninstallation action. Better yet, first try it on a copy of your site. If you tell it to kill your site it will do it without asking any questions.

**Comment by peterhulst** [comment]
Of course, I used it in a subdomain as test site (joomla4.loopgroepbedum.nl)
